# Example GitHub Actions Workflow for Auto-Deploying Documentation
# 
# To use this:
# 1. Copy this file to: .github/workflows/deploy-docs.yml (in your repository root)
# 2. Commit and push to GitHub
# 3. The workflow will automatically deploy docs on every push to main

name: Deploy Accordion Documentation

on:
  push:
    branches: [main, master]
    paths:
      - 'src/components/Accordion/**'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./src/components/Accordion/docs
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Comment on PR (if applicable)
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '📚 Documentation updated! View it at: ${{ steps.deployment.outputs.page_url }}'
            })

